# Site settings
title: Dev notes
author: Rocco Zanni
email: rocco.zanni@gmail.com
description: "A small blog about coding"
baseurl: ""
url: "http://roccozanni.com"
twitter_username: roccozanni
github_username:  roccozanni
analytics_id: UA-25976166-1

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
